spring:
  application:
    name: example-camel-idempotence-kafka

  cloud:
    service-registry:
      auto-registration:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      apache:
        camel:
          processor:
            idempotence: DEBUG

application:
  directory:
    inbound: /mnt/c/devtools/app/camel/inbound/
    working: /mnt/c/devtools/apps/camel/working/
    done: /mnt/c/devtools/app/camel/done/

  kafka:
    broker: 0.0.0.0:9092
    topics:
      idempotence: camel-idempotence
      announcements: camel-announcements

  camel:
    routes:
      idempotence: idempotence-consumer
      announcements: announcements-consumer