package org.kellyjones.examples.camel.routes;

import lombok.Getter;
import org.apache.camel.builder.RouteBuilder;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

@Getter
@Component
public class KafkaAnnouncementConsumerRoute extends AbstractKafkaConsumerRoute {

    // What Kafka broker will we consume from?
    @Value("${application.kafka.broker}")
    private String kafkaBrokers;

    // What Kafka topic is used for announcements generated by this app?
    @Value("${application.kafka.topics.announcements}")
    private String kafkaTopic;

    // When we create the corresponding Camel route,
    // what will its ID be?
    @Value("${application.camel.routes.announcements}")
    private String routeId;


}
